services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: restaurant_recommendation
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://restaurant_user:restaurant_password@db:5432/restaurant_recommendation

volumes:
  postgres_data:


